#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = -lpthread
LDFLAGS = 

INC_D_ALIB = $(INC)
CFLAGS_D_ALIB = $(CFLAGS) -g -DDEBUG
RESINC_D_ALIB = $(RESINC)
RCFLAGS_D_ALIB = $(RCFLAGS)
LIBDIR_D_ALIB = $(LIBDIR)
LIB_D_ALIB = $(LIB)
LDFLAGS_D_ALIB = $(LDFLAGS)
OBJDIR_D_ALIB = Objects/Debug
DEP_D_ALIB = 
OUT_D_ALIB = ../libs/libxtcpsock_d.a

INC_ALIB = $(INC)
CFLAGS_ALIB = $(CFLAGS) -O2
RESINC_ALIB = $(RESINC)
RCFLAGS_ALIB = $(RCFLAGS)
LIBDIR_ALIB = $(LIBDIR)
LIB_ALIB = $(LIB)
LDFLAGS_ALIB = $(LDFLAGS) -s
OBJDIR_ALIB = Objects/Release
DEP_ALIB = 
OUT_ALIB = ../libs/libxtcpsock.a

INC_LIB = $(INC)
CFLAGS_LIB = $(CFLAGS) -O2
RESINC_LIB = $(RESINC)
RCFLAGS_LIB = $(RCFLAGS)
LIBDIR_LIB = $(LIBDIR)
LIB_LIB = $(LIB)
LDFLAGS_LIB = $(LDFLAGS) -s
OBJDIR_LIB = Objects/Release
DEP_LIB = 
OUT_LIB = ../libs/xtcpsock.so

INC_D_LIB = $(INC)
CFLAGS_D_LIB = $(CFLAGS) -g -DDEBUG
RESINC_D_LIB = $(RESINC)
RCFLAGS_D_LIB = $(RCFLAGS)
LIBDIR_D_LIB = $(LIBDIR)
LIB_D_LIB = $(LIB)
LDFLAGS_D_LIB = $(LDFLAGS)
OBJDIR_D_LIB = Objects/Debug
DEP_D_LIB = 
OUT_D_LIB = ../libs/xtcpsock_d.so

OBJ_D_ALIB = $(OBJDIR_D_ALIB)/TCPClient.o $(OBJDIR_D_ALIB)/TCPServer.o $(OBJDIR_D_ALIB)/Threads.o

OBJ_ALIB = $(OBJDIR_ALIB)/TCPClient.o $(OBJDIR_ALIB)/TCPServer.o $(OBJDIR_ALIB)/Threads.o

OBJ_LIB = $(OBJDIR_LIB)/TCPClient.o $(OBJDIR_LIB)/TCPServer.o $(OBJDIR_LIB)/Threads.o

OBJ_D_LIB = $(OBJDIR_D_LIB)/TCPClient.o $(OBJDIR_D_LIB)/TCPServer.o $(OBJDIR_D_LIB)/Threads.o

all: d_alib alib lib d_lib

clean: clean_d_alib clean_alib clean_lib clean_d_lib

before_d_alib: 
	test -d ../libs || mkdir -p ../libs
	test -d $(OBJDIR_D_ALIB) || mkdir -p $(OBJDIR_D_ALIB)

after_d_alib: 

d_alib: before_d_alib out_d_alib after_d_alib

out_d_alib: before_d_alib $(OBJ_D_ALIB) $(DEP_D_ALIB)
	$(AR) rcs $(OUT_D_ALIB) $(OBJ_D_ALIB)

$(OBJDIR_D_ALIB)/TCPClient.o: TCPClient.c
	$(CC) $(CFLAGS_D_ALIB) $(INC_D_ALIB) -c TCPClient.c -o $(OBJDIR_D_ALIB)/TCPClient.o

$(OBJDIR_D_ALIB)/TCPServer.o: TCPServer.c
	$(CC) $(CFLAGS_D_ALIB) $(INC_D_ALIB) -c TCPServer.c -o $(OBJDIR_D_ALIB)/TCPServer.o

$(OBJDIR_D_ALIB)/Threads.o: Threads.c
	$(CC) $(CFLAGS_D_ALIB) $(INC_D_ALIB) -c Threads.c -o $(OBJDIR_D_ALIB)/Threads.o

clean_d_alib: 
	rm -f $(OBJ_D_ALIB) $(OUT_D_ALIB)
	rm -rf ../libs
	rm -rf $(OBJDIR_D_ALIB)

before_alib: 
	test -d ../libs || mkdir -p ../libs
	test -d $(OBJDIR_ALIB) || mkdir -p $(OBJDIR_ALIB)

after_alib: 

alib: before_alib out_alib after_alib

out_alib: before_alib $(OBJ_ALIB) $(DEP_ALIB)
	$(AR) rcs $(OUT_ALIB) $(OBJ_ALIB)

$(OBJDIR_ALIB)/TCPClient.o: TCPClient.c
	$(CC) $(CFLAGS_ALIB) $(INC_ALIB) -c TCPClient.c -o $(OBJDIR_ALIB)/TCPClient.o

$(OBJDIR_ALIB)/TCPServer.o: TCPServer.c
	$(CC) $(CFLAGS_ALIB) $(INC_ALIB) -c TCPServer.c -o $(OBJDIR_ALIB)/TCPServer.o

$(OBJDIR_ALIB)/Threads.o: Threads.c
	$(CC) $(CFLAGS_ALIB) $(INC_ALIB) -c Threads.c -o $(OBJDIR_ALIB)/Threads.o

clean_alib: 
	rm -f $(OBJ_ALIB) $(OUT_ALIB)
	rm -rf ../libs
	rm -rf $(OBJDIR_ALIB)

before_lib: 
	test -d ../libs || mkdir -p ../libs
	test -d $(OBJDIR_LIB) || mkdir -p $(OBJDIR_LIB)

after_lib: 

lib: before_lib out_lib after_lib

out_lib: before_lib $(OBJ_LIB) $(DEP_LIB)
	$(LD) -shared $(LIBDIR_LIB) $(OBJ_LIB)  -o $(OUT_LIB) $(LDFLAGS_LIB) $(LIB_LIB)

$(OBJDIR_LIB)/TCPClient.o: TCPClient.c
	$(CC) $(CFLAGS_LIB) $(INC_LIB) -c TCPClient.c -o $(OBJDIR_LIB)/TCPClient.o

$(OBJDIR_LIB)/TCPServer.o: TCPServer.c
	$(CC) $(CFLAGS_LIB) $(INC_LIB) -c TCPServer.c -o $(OBJDIR_LIB)/TCPServer.o

$(OBJDIR_LIB)/Threads.o: Threads.c
	$(CC) $(CFLAGS_LIB) $(INC_LIB) -c Threads.c -o $(OBJDIR_LIB)/Threads.o

clean_lib: 
	rm -f $(OBJ_LIB) $(OUT_LIB)
	rm -rf ../libs
	rm -rf $(OBJDIR_LIB)

before_d_lib: 
	test -d ../libs || mkdir -p ../libs
	test -d $(OBJDIR_D_LIB) || mkdir -p $(OBJDIR_D_LIB)

after_d_lib: 

d_lib: before_d_lib out_d_lib after_d_lib

out_d_lib: before_d_lib $(OBJ_D_LIB) $(DEP_D_LIB)
	$(LD) -shared $(LIBDIR_D_LIB) $(OBJ_D_LIB)  -o $(OUT_D_LIB) $(LDFLAGS_D_LIB) $(LIB_D_LIB)

$(OBJDIR_D_LIB)/TCPClient.o: TCPClient.c
	$(CC) $(CFLAGS_D_LIB) $(INC_D_LIB) -c TCPClient.c -o $(OBJDIR_D_LIB)/TCPClient.o

$(OBJDIR_D_LIB)/TCPServer.o: TCPServer.c
	$(CC) $(CFLAGS_D_LIB) $(INC_D_LIB) -c TCPServer.c -o $(OBJDIR_D_LIB)/TCPServer.o

$(OBJDIR_D_LIB)/Threads.o: Threads.c
	$(CC) $(CFLAGS_D_LIB) $(INC_D_LIB) -c Threads.c -o $(OBJDIR_D_LIB)/Threads.o

clean_d_lib: 
	rm -f $(OBJ_D_LIB) $(OUT_D_LIB)
	rm -rf ../libs
	rm -rf $(OBJDIR_D_LIB)

.PHONY: before_d_alib after_d_alib clean_d_alib before_alib after_alib clean_alib before_lib after_lib clean_lib before_d_lib after_d_lib clean_d_lib

